# Generated by Django 2.2 on 2019-04-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cur_lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='cur_long',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='driver_id',
            field=models.IntegerField(default=0),
        ),
    ]
